
```{r setup, warning=FALSE, include=FALSE, echo=FALSE, message=FALSE, output=FALSE}
library(knitr)
library(kableExtra)
library(formattable)

source('_code/wrc-api.R')
source('_code/wrc-wrangling.R')
source('_code/wrc-charts.R')
source('timing_sketches.R')
```

```{r setup_logger, echo=FALSE}
logFile = file("build.log", 'w') 
cat("Starting build", file=logFile, sep='\n')
```

```{r init_vars, warning=FALSE, include=FALSE, echo=FALSE, message=FALSE, output=FALSE}
# Load in event data
s = get_active_season()
eventId = get_eventId_from_name(s, 'italia')

itinerary = get_itinerary(eventId)
sections = get_sections(itinerary)
stages = get_stages(sections) #status and code are useful...

stages$cum_dist = cumsum(stages$distance)
stages$start_dist = c(0, stages$cum_dist[-length(stages$cum_dist)])


stages_lookup = get_stages_lookup(stages)

stage_cols = c('stageId', 'number', 'name', 'distance', 'code')
stage_info = stages %>%
                select(all_of(stage_cols)) %>%
                # Tidy up the stage name
                mutate(name = str_replace(name, ' \\(Live TV\\)', ''))
  
# For driver details
entries = get_rally_entries(eventId)
cars = get_car_data(entries)

# We can have customer entries which mess things up...
# TO DO - need to look this up properly

class_WRC_exclusions = c("C. FERAUD")
class_WRC = cars %>% filter(groupname=='WRC')  %>% 
                filter(!(drivername %in% class_WRC_exclusions)) %>% 
                select(entryId) 

class_WRC2 = cars %>% 
                  filter(startsWith(eligibility, 'WRC2')) %>%
                  select(entryId)

class_JWRC = cars %>% filter(eligibility=='JWRC') %>% select(entryId)

class_WRC3 = cars %>% filter(eligibility=='WRC3') %>% select(entryId)

#wrc = cars %>% filter(entryId<=22519)

target_class = class_WRC
use_group_rank = TRUE

wrc = cars %>% filter(entryId %in% target_class$entryId)
wrc_entries = wrc$entryId
```


```{r echo=FALSE}
cat("Done setup", file=logFile, sep='\n')
```
# Overall Standings {-}

*Summary reports of overall standings and stage results.*

```{r  message=FALSE, echo=FALSE, error=FALSE, warning=FALSE, results='asis'}
#stage_list=list("SS1", "SS2", "SS3", "SS4", "SS5", "SS6", "SS7", "SS8", "SS9", "SS10", "SS11", "SS12", "SS13", "SS14", "SS15", "SS16", "SS17", "SS18", "SS19", "SS20")
stage_list=list("SS1", "SS2", "SS3", "SS4", "SS5", "SS6", "SS7")
omit_stage_splits = c()

cutoff_delta = -1 #1500000 # if negative ignore

src = knit_expand("overall-template.Rmd")
    cat(knit_child(text=src,
                 options = list(echo=FALSE, warning=FALSE, error=FALSE),
                 quiet=TRUE))
```

# Loop Reports {-}

*Forthcoming... summary reports for each loop.*

```{r looper, message=FALSE, echo=FALSE, error=FALSE, warning=FALSE, results='asis'}

#stage_list=list("SS1","SS2")
for (stage_code in stage_list){
  stageId = stages_lookup[[stage_code]]
  stage_times = get_stage_times(eventId, stageId)

  stage_info_ = stage_info[stage_info['stageId']==stageId,]
 
  src = knit_expand("stage_result_template.Rmd")
    cat(knit_child(text=src,
                 options = list(echo=FALSE, warning=FALSE, error=FALSE),
                 quiet=TRUE))
}
```

```{r end_logger, echo=FALSE}
cat("Finished build", file=logFile, sep='\n')
```
